apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-url-configmap
data:
  EXTERNAL_PRODUCT_SERVICE_BASE_URL: http://shopbuddy.com/product
  EXTERNAL_AUTH_SERVER_BASE_URL: http://shopbuddy.com/auth
  EXTERNAL_STOREFRONT_CHANNEL_BASE_URL: http://shopbuddy.com/storefront

  INTERNAL_PRODUCT_SERVICE_BASE_URL: http://product-service:8080/product
  INTERNAL_AUTH_SERVER_BASE_URL: http://auth-service:8080/auth
  INTERNAL_USER_SERVICE_BASE_URL: http://user-service:8080
