#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-production
#spec:
#  acme:
#    # Letâ€™s Encrypt staging endpoint for testing
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: iann.agasen@gmail.com
#    privateKeySecretRef:
#      name: letsencrypt-prod-account-key
#    solvers:
#      - http01:
#          ingress:
#            ingressClassName: nginx