apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-admin
  name: k8s-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: k8s-admin
    spec:
      serviceAccountName: k8s-admin-sa
      containers:
        - name: k8s-admin
          image: k8s-admin:latest
          imagePullPolicy: Never # recommended for local development
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 5005
              name: debug
          envFrom:
            - configMapRef:
                name: backend-url-configmap
          env:
            - name: JAVA_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"