apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-admin-rolebinding
  namespace: default  # Same namespace
subjects:
  - kind: ServiceAccount
    name: k8s-admin-sa
    namespace: default
roleRef:
  kind: Role
  name: k8s-admin-role
  apiGroup: rbac.authorization.k8s.io