apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-main
spec:
  rules:
    - host: "shopbuddy.com"
      http:
        paths:
          - pathType: Prefix
            path: "/product"
            backend:
              service:
                name: product-service
                port:
                  number: 8080