apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-gui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    #  Redis does not support path rewriting so will need to use subdomain
    - host: "redis.shopbuddy.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-gui-service
                port:
                  number: 5540