## ingress-product-swagger.yaml - No rewrite for Swagger
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-product-swagger
#spec:
#  rules:
#    - host: "shopbuddy.com"
#      http:
#        paths:
#          - pathType: Prefix
#            path: "/product/swagger-ui"
#            backend:
#              service:
#                name: product-service
#                port:
#                  number: 8080
#          - pathType: Prefix
#            path: "/product/swagger-ui.html"
#            backend:
#              service:
#                name: product-service
#                port:
#                  number: 8080
#          - pathType: Prefix
#            path: "/product/v3/api-docs"
#            backend:
#              service:
#                name: product-service
#                port:
#                  number: 8080