apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "shopbuddy.com"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/gateway(/|$)(.*)"  # Regex to capture everything after /product
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080