apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-app-ingress
  annotations:
    # Enable regex matching
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Rewrite using captured group $2
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    cert-manager.io/cluster-issuer: "shopbuddy-mkcert-tls"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shopbuddy.com
      secretName: shopbuddy-mkcert-tls
  rules:
    - host: shopbuddy.com
      http:
        paths:
          - path: /storefront(/|$)(.*)
            #               │    │
            #               │    └─ Capture group $2 (everything after /storefront/)
            #               └────── Capture group $1 (/ or end of line)
            pathType: ImplementationSpecific
            backend:
              service:
                name: storefront-service
                port:
                  number: 80